---
- name: List EC2 Instances
  hosts: 172.31.90.245
  tasks:
    - name: Get running EC2 instances
      ec2_instance_facts:
        region: us-east-1
        filters:
          "instance-state-name": "running"
      register: ec2_instances
    - name: Format EC2 Instances
      set_fact:
        ec2_table: |
          Instance ID\tInstance Name\tInstance Type\tPrivate IP\tPublic IP
          {% for instance in ec2_instances.instances %}
          {{ instance.id }}\t{{ instance.tags.Name if instance.tags.Name else "N/A" }}\t{{ instance.instance_type }}\t{{ instance.private_ip_address }}\t{{ instance.public_ip_address }}
          {% endfor %}
#- name: Send EC2 Instances List
  #mail:
    host: 172.31.90.245
    port: 587
    username: awx
    password: Infy@123
    to: meghana_ch@yahoo.com
    subject: "Daily EC2 Instance List"
    body: "{{ ec2_table }}"
  delegate_to: localhost
